/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum TipMeciDTO
{
  CALIFICARE = 1,
  SAISPREZECIME = 2,
  OPTIME = 3,
  SFERT = 4,
  SEMIFINALA = 5,
  FINALA = 6,
}
