/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package model.domain;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-04-30")
public enum TipMeciDTO implements org.apache.thrift.TEnum {
  CALIFICARE(1),
  SAISPREZECIME(2),
  OPTIME(3),
  SFERT(4),
  SEMIFINALA(5),
  FINALA(6);

  private final int value;

  private TipMeciDTO(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TipMeciDTO findByValue(int value) { 
    switch (value) {
      case 1:
        return CALIFICARE;
      case 2:
        return SAISPREZECIME;
      case 3:
        return OPTIME;
      case 4:
        return SFERT;
      case 5:
        return SEMIFINALA;
      case 6:
        return FINALA;
      default:
        return null;
    }
  }
}
